name: Szip CI / CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-unix:
    name: Build & Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Sxzip
      run: cmake --build build --config Release -j 4

    - name: Copy executable for testing
      run: cp build/sxzip test/sxzip

    - name: Run Szip Core Benchmark & Integrity Test
      working-directory: test
      run: |
        chmod +x a.sh
        ./a.sh 100

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Sxzip (MSVC)
      run: cmake --build build --config Release -j 4
